### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by rutchkiwi** [xiaozhuai/jetbrains-jump-to-file#1]
Hi! I really want the feature.
But how do I actually use it?
I use cursvie for clojure, and no popups or context actions come up..

Thanks!

**Comment by xiaozhuai** [comment]
Hi @rutchkiwi . I'm sorry to tell you that currently clojure is not in support list.

**Comment by rutchkiwi** [comment]
Ah, sad. I was hoping that since Cursive (the Clojure plugin) somehow tags up string literals for the rest of IntelliJ to use, this plugin could just use that without modifications. Thanks for the reply anyhow!

**Comment by xiaozhuai** [comment]
> Ah, sad. I was hoping that since Cursive (the Clojure plugin) somehow tags up string literals for the rest of IntelliJ to use, this plugin could just use that without modifications. Thanks for the reply anyhow!

I've reopen this issue. Clojure support will come soon.

**Comment by rutchkiwi** [comment]
would be much appreciated! :)

**Comment by xiaozhuai** [comment]
I've release a new version `1.1.0` which supports clojure (via cursive).
It is now pending JetBrains' review and approval.

You can download and install it manully, please let me know if it works or not.
[jetbrains-jump-to-file-1.1.0.zip](https://github.com/xiaozhuai/jetbrains-jump-to-file/files/14916425/jetbrains-jump-to-file-1.1.0.zip)

**Comment by rutchkiwi** [comment]
It works perfectly. Thank you so much!! :D

**Comment by xiaozhuai** [comment]
Thanks for reporting this.
