### ISSUE TITLE
[feature request] Find usages of file

### ISSUE THREAD

**Issue by rutchkiwi** [xiaozhuai/jetbrains-jump-to-file#2]
Thanks for adding the clojure support, it's been really useful!

I was wondering if you know of any way to do the opposite of jumping to file - i.e enabling "find usage" when I've got a file open?
My project uses a lot of HTML templates, and I often start from the template. And then I want to jump to where the file is referenced in code.
I have no idea of the feasibility of such a feature but seems like this plugin already does the important part, identifying a mapping of strings -> files. (but in this case it'd be the other way)

**Comment by xiaozhuai** [comment]
Hello @rutchkiwi . That's a good idea indeed. I'll look into it later.

**Comment by xiaozhuai** [comment]
I believe it can be achieved through [Find Usages Provider](https://plugins.jetbrains.com/docs/intellij/find-usages-provider.html#define-a-find-usages-provider).

**Comment by xiaozhuai** [comment]
Hello @rutchkiwi 

I've release a new version 1.1.4 which supported find usages by file.

Choose a file in project file list, and press Option+F7 (on macOS) or right click the file and then click Find Usages.


It is now pending JetBrains' review and approval.

You can download and install it manully, please let me know if it works or not.

[jetbrains-jump-to-file-1.1.4.zip](https://github.com/xiaozhuai/jetbrains-jump-to-file/files/15161475/jetbrains-jump-to-file-1.1.4.zip)

**Comment by rutchkiwi** [comment]
Works amazingly!

Thanks a lot! :)
